[marketing]
    apiKey = 'AIzaSyD8gVrQX3jRzo9nerowK6u6yQXyvvHNrpE'
    projectId = 'fintual-staging'
    messagingSenderId = '619577264252'
    appId = '1:619577264252:web:53c764a26bc36ac0eb61f9'
    measurementId = 'G-P7KYWD4YN6'
