[marketing]
    apiKey = 'AIzaSyDiCpuQ3E0buhvX4EF_24bRl0D0H_ripmg'
    projectId = 'numeric-citron-252119'
    messagingSenderId = '20719183767'
    appId = '1:20719183767:web:cd8a5df90d73c3b8a386d2'
    measurementId = 'G-R2RMXT8VRK'
