---
label: default
hide_body: false
fields:
- name: author
  type: select
  default: Omar Larré
  config:
    required: true
    options:
    - Pedro Pineda
    - Omar Larré
    - Andrés Marinkovic
    - Agustín Feuerhake
    - Francesca Finaldi
    - Gonzalo Enei
    - Juan Francisco Weitz
    - Matías Hurtado
    - Victor Hugo Flores
    - Jessica Guzmán
    - Montserrat Bonilla
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Author
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  config:
    required: true
- name: image
  type: file
  config:
    maxSize: 250
  label: Image
  description: will show on link previews
- type: text
  name: description
  label: Description
- type: list
  name: categories
  label: Categories
  config:
    min: '0'
    max: '5'
    use_select: true
    source:
      type: simple
      section: posts
    options:
    - " clases"
    - educación financiera
    - entrevistas
    - noticias
    - podcasts
- type: datetime
  name: date
  label: Date
  config:
    date_format: YYYY-MM-DD
    required: true
  default: now
- type: text
  name: url
  label: Url
  config:
    required: true
- type: list
  name: aliases
  label: Aliases
  description: additional urls
  config:
    use_select: false
- name: hide
  type: boolean
  label: Hide
  description: para esconder el post en edu (el link sigue funcionando)
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/post/5-errores-clásicos-al-ahorrar-o-invertir.md
- content/post/afores-ahorro-y-sistema-de-pensiones-en-méxico-a-punto-del-colapso.md
- content/post/cómo-un-café-menos-al-día-podría-darte-hasta-2-millones-de-pesos.md
- content/post/esto-es-ahorrar-con-fintual.md
- content/post/sobrevive-la-cuesta-y-aprende-a-ahorrar.md
