---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: text
  name: image
  label: image
  description: image used on links
- type: text
  name: description
  label: Description
- type: list
  name: aliases
  label: aliases
  config:
    min: '0'
    max: '5'
- type: list
  name: categories
  label: Categories
  config:
    min: '0'
    max: '5'
    use_select: false
    source:
      type: simple
- type: datetime
  name: date
  label: Date
  config:
    date_format: YYYY-MM-DD
    required: true
pages:
- content/post/sherlock.md
- content/post/1-año-de-fintual-y-sus-fondos.md
