---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/comprar-tiempo-es-mejor-que-comprar-relojes.md
- content/renta-poco-el-deposito-a-plazo-.md
- content/como-invertir-dinero-en-chile.md
- content/inversion-online-en-chile-desde--5.000.md
- content/fondo-mutuo-online.md
- content/que-es-un-robotadvisor-y-por-que-te-conviene-.md
