---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: text
  name: image
  label: image
  description: image used on links
- type: text
  name: description
  label: Description
- type: list
  name: categories
  label: Categories
  config:
    min: '0'
    max: '5'
    use_select: false
    source:
      type: simple
- type: datetime
  name: date
  label: Date
  config:
    date_format: YYYY-MM-DD
    required: true
- type: text
  name: url
  label: url
  config:
    required: true
- type: text
  name: author
  label: Author
- type: file
  name: author_thumbnail
  label: Author Thumbnail
pages:
- content/post/por-qué-los-fondos-mutuos-rentan-tan-poco-78a9aafc9896.md
- content/post/fintalks-ep-1-sobre-la-reforma-previsional.md
- content/post/fintalks-ep-2-apv-y-seguros-con-ahorro.md
- content/post/fintalks-ep-1-sobre-la-reforma-previsional-1.md
- content/post/finclass-clase-1-qué-es-un-fonto-mutuo-cómo-invertir-en-etfs.md
- content/post/por-qué-las-afps-podrían-invertir-mejor-y-no-lo-hacen-3f620e036402.md
- content/post/pocas-mujeres-en-el-mundo-financiero-76c31a395a3f.md
- content/post/por-qué-cayó-tanto-el-fondo-e-de-las-afp-donald-trump-y-los-simpsons-e17fffedbddb.md
- content/post/sherlock.md
- content/post/1-ano-de-fintual-y-sus-fondos.md
