---
label: default
hide_body: false
fields:
- name: author
  type: select
  default: []
  config:
    required: true
    options:
    - Pedro Pineda
    - Omar Larré
    - Andrés Marinkovic
    - Agustín Feuerhake
    - Francesca Finaldi
    - Gonzalo Enei
    - Juan Francisco Weitz
    - Matías Hurtado
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Author
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  config:
    required: true
- name: image
  type: file
  config:
    maxSize: 250
  label: Image
  description: will show on link previews
- type: text
  name: description
  label: Description
- type: list
  name: categories
  label: Categories
  config:
    min: '0'
    max: '5'
    use_select: true
    source:
      type: simple
      section: posts
    options:
    - " clases"
    - educación financiera
    - entrevistas
    - noticias
    - podcasts
- type: datetime
  name: date
  label: Date
  config:
    date_format: YYYY-MM-DD
    required: true
  default: now
- type: text
  name: url
  label: Url
  config:
    required: true
- type: list
  name: aliases
  label: Aliases
  description: additional urls
  config:
    use_select: false
- name: hide
  type: boolean
  label: Hide
  description: para esconder el post en edu (el link sigue funcionando)
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/post/el-banco-central-de-chile-volvió-a-bajar-las-tasas.md
- content/post/explicación.md
- content/post/cuánta-plata-debería-tener-en-mi-cuenta-corriente.md
- content/post/súper-ricos-y-fintual.md
- content/post/auto-o-uber.md
- content/post/y-a-mí-qué-me-importa-que-bajen-las-tasas.md
- content/post/finclass-finanzas-aplicadas-y-fintech-clase-2.md
- content/post/clase-5-riesgo-y-aleatoriedad.md
- content/post/finclass-finanzas-aplicadas-y-fintech-clase-3.md
- content/post/4-formas-simples-de-bajar-tus-impuestos-usando-fintual.md
- content/post/fintual-tiene-us-250-000-para-repartir-en-su-plan-de-recompensas-para
  hackers.md
- content/post/lunes-negro-en-wall-street.md
- content/post/clase-9-mercados-y-teoría-de-portafolios.md
- content/post/cómo-convencer-a-un-amigo-de-que-fintual-le-conviene.md
- content/post/file.md
- content/post/clase-6-eventos-de-cola-burbujas-y-sesgos-conductuales-fallas-de-procesos-estadísticos.md
- content/post/finclass-clase-1-qué-es-un-fonto-mutuo-cómo-invertir-en-etfs.md
- content/post/clase-8-cobertura-y-componentes-principales.md
- content/post/cómo-tener-un-poco-de-suerte-al-invertir-en-fintual-95c42d6b850c.md
- content/post/clase-7-riesgos-errores-de-modelo-sesgos-conductuales-casos.md
- content/post/1-ano-de-fintual-y-sus-fondos.md
- content/post/como-ahorrar-para-lo-que-quieres.md
- content/post/por-qué-cayó-tanto-el-fondo-e-de-las-afp-donald-trump-y-los-simpsons-e17fffedbddb.md
- content/post/como-un-cafe-menos-al-dia-podria-darte-mas-de-100mm.md
- content/post/fintalks-ep-2-apv-y-seguros-con-ahorro.md
- content/post/fintalks-ep-4-proyecciones-de-mercado.md
- content/post/fintalks-ep-6-axel-christensen-en-fintual.md
- content/post/cómo-elegir-bien-el-riesgo-de-tus-distintas-inversiones.md
- content/post/automatizando-tus-finanzas-personales.md
- content/post/te-cagaste-de-frío-este-invierno.md
- content/post/ctm-las-comisiones-te-matan.md
- content/post/te-cuesta-ahorrar.md
- content/post/por-qué-las-afps-podrían-invertir-mejor-y-no-lo-hacen-3f620e036402.md
- content/post/por-qué-los-fondos-mutuos-rentan-tan-poco-78a9aafc9896.md
- content/post/sherlock.md
- content/post/pocas-mujeres-en-el-mundo-financiero-76c31a395a3f.md
- content/post/fintalks-ep-7-fintual-en-y-combinator.md
- content/post/fintalks-ep-1-sobre-la-reforma-previsional.md
- content/post/fintalks-ep-1-sobre-la-reforma-previsional-1.md
- content/post/fintalks-ep-5-monopolio-en-los-medios-de-pago.md
- content/post/ejemplo-de-riesgo-diversificado-en-el-tiempo.md
- content/post/finclass-finanzas-aplicadas-y-fintech-clase-1.md
- content/post/finclass-casos-bancos-centrales-tasas-de-interés-y-el-concepto-del-dinero-clase-4.md
- content/post/finclass-riesgo-y-aleatoriedad-clase-5.md
