---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: text
  name: image
  label: image
  description: image used on links
pages:
- content/si-eres-de-cornershop-te-queremos-regalar-una-pizza.md
- content/renta-poco-el-deposito-a-plazo-.md
- content/si-estas-en-socrates-te-queremos-regalar-una-pizza.md
- content/como-invertir-dinero-en-chile.md
- content/inversion-online-en-chile-desde--5.000.md
- content/aumento-de-sueldo.md
- content/mejor-deposito-a-plazo.md
- content/impuesto-a-la-herencia.md
- content/como-las-7-lucas-del-confort-podrian-ser-mas-de--300.000.md
- content/-compra-de-departamentos-.md
- content/invierte-palta.md
- content/-en-que-invertir-el-bono-del-trabajo-.md
- content/cuota-de-incorporacion-a-colegio.md
- content/fondo-mutuo-online.md
- content/comprar-tiempo-es-mejor-que-comprar-relojes.md
- content/-invertir-en-acciones-.md
- content/la-bicicleta-mas-cara.md
- content/cuenta-2.md
- content/simulador-de-inversiones.md
- content/beneficios-tributarios.md
- content/invertir-en-fondos-mutuos..md
- content/el-mejor-cafe-es-el-que-inviertes..md
- content/simulador-de-fondos-mutuos.md
- content/depositos-a-plazo..md
- content/ctm--las-comisiones-te-matan.md
- content/mas-tiempo-y-menos-iphones.md
- content/que-es-un-robotadvisor-y-por-que-te-conviene-.md
