---
label: default
hide_body: false
fields:
- name: author
  type: select
  default: Omar Larré
  config:
    required: true
    options:
    - Pedro Pineda
    - Omar Larré
    - Andrés Marinkovic
    - Agustín Feuerhake
    - Francesca Finaldi
    - Gonzalo Enei
    - Juan Francisco Weitz
    - Matías Hurtado
    - Victor Hugo Flores
    - Jessica Guzmán
    - Montserrat Bonilla
    - Valentin Jadot
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Author
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  config:
    required: true
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
  description: will show on link previews
- type: text
  name: description
  label: Description
- type: list
  name: categories
  label: Categories
  config:
    min: '0'
    max: '5'
    use_select: true
    source:
      type: simple
      section: posts
    options:
    - " clases"
    - educación financiera
    - entrevistas
    - noticias
    - podcasts
- type: datetime
  name: date
  label: Date
  config:
    date_format: YYYY-MM-DD
    required: true
  default: now
- type: text
  name: url
  label: Url
  config:
    required: true
- type: list
  name: aliases
  label: Aliases
  description: additional urls
  config:
    use_select: false
- name: hide
  type: boolean
  label: Hide
  description: para esconder el post en edu (el link sigue funcionando)
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/post/5-errores-clásicos-al-ahorrar-o-invertir.md
- content/post/6-puntos-para-entender-sobre-impuestos-al-invertir-en-fondos.md
- content/post/afores-ahorro-y-sistema-de-pensiones-en-méxico-a-punto-del-colapso.md
- content/post/cuando-supe-por-qué-crearon-las-afores-entendí-por-qué-son-importantes.md
- content/post/cómo-un-café-menos-al-día-podría-darte-hasta-2-millones-de-pesos.md
- content/post/elige-tu-afore-como-si-fuera-lo-que-usaras-en-una-boda.md
- content/post/en-que-invertir-mi-dinero.md
- content/post/esto-es-ahorrar-con-fintual.md
- content/post/fintual-discovery-educacion-financiera-facil-simple-y-gratis-copy.md
- content/post/por-qué-fintual.md
- content/post/renuncie-a-gastar-mis-utilidades-e-hice-esto.md
- content/post/sobrevive-la-cuesta-y-aprende-a-ahorrar.md
- content/post/todo-lo-que-tienes-que-saber-sobre-las-pensiones-en-mexico.md
